return blank cleanup func for plugin.InmemCreationFunc
hashicorp/go-secure-stdlib pull request #117
Opened 2024-02-06 07:57 UTC by bosorawis

Return a blank cleanup func instead of `nil` to prevent accidental panic from `defer cleanup()`

2024-02-06 15:35 UTC, guygrigsby approved these changes

2024-02-06 19:39 UTC, jefferai commented
This looks good - wherever you saw the panic can you also add a nil check there? Not sure if it was in this package or elsewhere.

2024-02-07 10:55 UTC, bosorawis commented
@jefferai I ran into the panic in HCP Boundary code, not sure it also happens elsewhere. This PR is referenced above

2024-02-07 20:04 UTC, jefferai approved these changes

2024-02-07 20:07 UTC, jefferai requested changes
On line 254 we create a cleanup func that is returned in success scenarios; depending on various conditions we modify that cleanup func later. Rather than create a func inline here, can you move creation of that cleanup above this (but returning nil) and simply reassign it on line 254?

That just keeps the return pattern consistent throughout.

2024-02-08 10:08 UTC, bosorawis commented
@jefferai done! thank you!

2024-02-13 02:17 UTC, merged

2024-02-13 02:18 UTC, jefferai commented
Tagged v2.0.7.